use bevy::prelude::*;

#[derive(Debug, Clone)]
pub struct UiColorPalettes {
    pub white: UiColorPaletteBasic,
    pub black: UiColorPaletteBasic,
    pub gray: UiColorPalette,
    pub mauve: UiColorPalette,
    pub slate: UiColorPalette,
    pub sage: UiColorPalette,
    pub olive: UiColorPalette,
    pub sand: UiColorPalette,
    pub tomato: UiColorPalette,
    pub red: UiColorPalette,
    pub ruby: UiColorPalette,
    pub crimson: UiColorPalette,
    pub pink: UiColorPalette,
    pub plum: UiColorPalette,
    pub purple: UiColorPalette,
    pub violet: UiColorPalette,
    pub iris: UiColorPalette,
    pub indigo: UiColorPalette,
    pub blue: UiColorPalette,
    pub cyan: UiColorPalette,
    pub teal: UiColorPalette,
    pub jade: UiColorPalette,
    pub green: UiColorPalette,
    pub grass: UiColorPalette,
    pub bronze: UiColorPalette,
    pub brown: UiColorPalette,
    pub gold: UiColorPalette,
    pub sky: UiColorPalette,
    pub mint: UiColorPalette,
    pub lime: UiColorPalette,
    pub yellow: UiColorPalette,
    pub amber: UiColorPalette,
    pub orange: UiColorPalette,
}
pub enum UiColorPalettesName {
    Gray,
    Mauve,
    Slate,
    Sage,
    Olive,
    Sand,
    Tomato,
    Red,
    Ruby,
    Crimson,
    Pink,
    Plum,
    Purple,
    Violet,
    Iris,
    Indigo,
    Blue,
    Cyan,
    Teal,
    Jade,
    Green,
    Grass,
    Bronze,
    // Brown,
    Gold,
    // Sky,
    // Mint,
    // Lime,
    // Yellow,
    // Amber,
    // Orange,
}
pub struct UiColorPalettesData(pub UiColorPalettes);

#[derive(Debug, Clone, PartialEq)]
pub struct UiColorPalette {
    pub base: Color,
    pub bg_subtle: Color,
    pub bg: Color,
    pub bg_hover: Color,
    pub bg_active: Color,
    pub line: Color,
    pub border: Color,
    pub border_hover: Color,
    pub solid: Color,
    pub solid_hover: Color,
    pub text: Color,
    pub text_contrast: Color,
    pub base_a: Color,
    pub bg_subtle_a: Color,
    pub bg_a: Color,
    pub bg_hover_a: Color,
    pub bg_active_a: Color,
    pub line_a: Color,
    pub border_a: Color,
    pub border_hover_a: Color,
    pub solid_a: Color,
    pub solid_hover_a: Color,
    pub text_a: Color,
    pub text_contrast_a: Color,

    pub high_contrast: Color,
    pub surface: Color,
    pub indicator: Color,
    pub track: Color,
}
#[derive(Debug, Clone, PartialEq)]
pub struct UiColorPaletteBasic {
    pub base: Color,
    pub bg_subtle: Color,
    pub bg: Color,
    pub bg_hover: Color,
    pub bg_active: Color,
    pub line: Color,
    pub border: Color,
    pub border_hover: Color,
    pub solid: Color,
    pub solid_hover: Color,
    pub text: Color,
    pub text_contrast: Color,
}

/// Verschiedene Kontraststufen für Textfarben
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TextContrastLevel {
    /// Geringer Kontrast für sekundären Text (z.B. Beschreibungen)
    Low,
    /// Mittlerer Kontrast für normalen Text
    Medium,
    /// Hoher Kontrast für wichtigen Text (WCAG AA: ≥4.5:1)
    High,
    /// Barrierefreier Kontrast (WCAG AAA: ≥7:1)
    Accessible,
}
